#!/bin/bash

# TODO: Check palet thing after size
SIZE="crop=2160:3000:0:500,fps=15,scale=300:-2"

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -y alfa.webp

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -vcodec libwebp \
    -y bravo.webp

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -vcodec libwebp \
    -compression_level 0 \
    -y charlie.webp

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -vcodec libwebp \
    -compression_level 1 \
    -y delta.webp

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -vcodec libwebp \
    -compression_level 2 \
    -y echo.webp

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -vcodec libwebp \
    -compression_level 3 \
    -y foxtrot.webp

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -vcodec libwebp \
    -compression_level 4 \
    -y golf.webp

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -vcodec libwebp \
    -compression_level 5 \
    -y hotel.webp

ffmpeg -i input.mp4 \
    -vf "$SIZE" \
    -loop 0 \
    -vcodec libwebp \
    -compression_level 6 \
    -y india.webp



# -compression_level 0
# -quality 85 
# -preset default
